name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Set up Python
        uses: actions/setup-python@v6

      - name: Run pre-commit
        uses: https://git.iamthefij.com/iamthefij/pre-commit-action@v3.0.2
